<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>BungeeWeb</groupId>
	<artifactId>BungeeWeb</artifactId>
	<name>BungeeWeb</name>
	<version>2.1.0-SNAPSHOT</version>
	<properties>
		<package>io.github.dead_i.bungeeweb</package>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<pluginId>bungeeweb</pluginId>
		<pluginName>BungeeWeb</pluginName>
	</properties>
	<build>
		<sourceDirectory>src</sourceDirectory>
		<defaultGoal>clean package</defaultGoal>
		<directory>target</directory>
		<finalName>VelocityWeb-${version}</finalName>
		<plugins>
			<!-- Replacer Plugin -->
			<plugin>
				<groupId>com.google.code.maven-replacer-plugin</groupId>
				<artifactId>replacer</artifactId>
				<version>1.5.3</version>
				<executions>				
					<execution>
						<phase>prepare-package</phase>
						<goals>
							<goal>replace</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<basedir>${project.build.directory}/classes</basedir>
					<includes>
						<include>velocity-plugin.json</include>
					</includes>
					<replacements>
						<replacement>
							<token>id----</token>
							<value>${pluginId}</value>
						</replacement>
						<replacement>
							<token>@pluginName@</token>
							<value>${pluginName}</value>
						</replacement>
						<replacement>
							<token>@version@</token>
							<value>${version}</value>
						</replacement>
						<replacement>
							<token>@author@</token>
							<value>${author}</value>
						</replacement>
						<replacement>
							<token>@description@</token>
							<value>${description}</value>
						</replacement>
						<replacement>
							<token>@url@</token>
							<value>${website}</value>
						</replacement>
					</replacements>						
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.11.0</version>
				<configuration>
					<source>17</source>
					<target>17</target>
					<release>17</release>
					<showDeprecation>true</showDeprecation>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>3.5.0</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<filters>
								<filter>
									<artifact>*</artifact>
									<excludes>
										<exclude>META-INF/*.SF</exclude>
										<exclude>META-INF/*.RSA</exclude>
										<exclude>META-INF/*.INF</exclude>
									</excludes>
								</filter>
							</filters>
						</configuration>
					</execution>
				</executions>
				<configuration>
					<relocations>
						<relocation>
							<pattern>com.zaxxer</pattern>
							<shadedPattern>${package}.lib.com.zaxxer</shadedPattern>
						</relocation>
						<!-- Yes, I'm monster not programmer. I use relocation to replace variables -->
						<relocation>
							<!-- Alphanumeric only... -->
							<pattern>id----</pattern>
							<shadedPattern>${pluginId}</shadedPattern>
						</relocation>
						<relocation>
							<pattern>@pluginName@</pattern>
							<shadedPattern>${pluginName}</shadedPattern>
						</relocation>
						<relocation>
							<pattern>@version@</pattern>
							<shadedPattern>${version}</shadedPattern>
						</relocation>
						<relocation>
							<pattern>@author@</pattern>
							<shadedPattern>${author}</shadedPattern>
						</relocation>
						<relocation>
							<pattern>@description@</pattern>
							<shadedPattern>${description}</shadedPattern>
						</relocation>
					</relocations>
				</configuration>
			</plugin>
		</plugins>
		<resources>
			<resource>
				<targetPath>.</targetPath>
				<directory>${project.basedir}</directory>
				<filtering>true</filtering>
				<includes>
					<include>README.md</include>
					<include>LICENCE.md</include>
				</includes>
			</resource>
			<resource>
				<targetPath>.</targetPath>
				<directory>resources</directory>
				<filtering>false</filtering>
			</resource>
		</resources>
	</build>
	<repositories>
		<repository>
			<id>sonatype</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots/</url>
		</repository>
	</repositories>
	<dependencies>
		<!-- Annotations -->
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.28</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.jetbrains</groupId>
			<artifactId>annotations</artifactId>
			<version>24.0.1</version>
			<scope>provided</scope>
		</dependency>
		<!-- Velocity -->
		<dependency>
			<groupId>com.velocitypowered</groupId>
			<artifactId>velocity-api</artifactId>
			<version>3.3.0-SNAPSHOT</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.zaxxer</groupId>
			<artifactId>HikariCP</artifactId>
			<version>5.0.1</version>
			<type>jar</type>
			<scope>compile</scope>
		</dependency>
		<!-- Jetty -->
		<dependency>
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>jetty-server</artifactId>
			<version>11.0.15</version>
			<type>jar</type>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>jetty-servlet</artifactId>
			<version>11.0.15</version>
			<type>jar</type>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>javax.activation</groupId>
			<artifactId>activation</artifactId>
			<version>1.1.1</version>
			<type>jar</type>
			<scope>compile</scope>
		</dependency>
		<!--dependency>
			<groupId>org.mariadb.jdbc</groupId>
			<artifactId>mariadb-java-client</artifactId>
			<version>3.5.1</version>
			<type>jar</type>
			<scope>compile</scope>
		</dependency-->
	</dependencies>
</project>